# Importing all the required libraries

In [14]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler

# Loading the dataset

In [15]:
df = pd.read_csv('prime_data.csv', encoding='latin-1')
df.head()

,S.no.,Name of the show,Year of release,No of seasons available,Language,Genre,IMDb rating,Age of viewers
0,1,Pataal Lok,2020.0,1.0,Hindi,Drama,7.5,18+
1,2,Upload,2020.0,1.0,English,Sci-fi comedy,8.1,16+
2,3,The Marvelous Mrs. Maisel,2017.0,3.0,English,"Drama, Comedy",8.7,16+
3,4,Four More Shots Please,2019.0,2.0,Hindi,"Drama, Comedy",5.3,18+
4,5,Fleabag,2016.0,2.0,English,Comedy,8.7,18+

# Extracting the infromation about the dataset

In [16]:
print(df.info())
print(df.describe())
print(df.isnull())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   S.no.                    404 non-null    int64
 1   Name of the show         393 non-null    object
 2   Year of release          393 non-null    float64
 3   No of seasons available  393 non-null    float64
 4   Language                 393 non-null    object
 5   Genre                    393 non-null    object
 6   IMDb rating              182 non-null    float64
 7   Age of viewers           393 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 25.4+ KB
None
            S.no.  Year of release  No of seasons available  IMDb rating
count  404.000000       393.000000               393.000000   182.000000
mean   202.500000      2011.279898                 2.608142     7.354396
std    116.769003        12.944861                 2.592008     0.959372
min      1.000000      1926.000000                 1.000000     3.700000
25%    101.750000      2011.000000                 1.000000     6.900000
50%    202.500000      2016.000000                 2.000000     7.500000
75%    303.250000      2018.000000                 3.000000     8.100000
max    404.000000      2020.000000                20.000000     9.000000
     S.no.  Name of the show  Year of release  No of seasons available  \
0    False             False            False                    False
1    False             False            False                    False
2    False             False            False                    False
3    False             False            False                    False
4    False             False            False                    False
..     ...               ...              ...                      ...
399  False              True             True                     True
400  False              True             True                     True
401  False              True             True                     True
402  False              True             True                     True
403  False              True             True                     True

     Language  Genre  IMDb rating  Age of viewers
0       False  False        False           False
1       False  False        False           False
2       False  False        False           False
3       False  False        False           False
4       False  False        False           False
..        ...    ...          ...             ...
399      True   True         True            True
400      True   True         True            True
401      True   True         True            True
402      True   True         True            True
403      True   True         True            True

[404 rows x 8 columns]
(404, 8)

# Performing the pre-processing on the dataset

In [17]:
# handling missing values
df['Name of the show'].isnull().sum()
columns = df.columns

for cols in columns:
    if df[cols].isnull().sum() > 1:
        df[cols].fillna(method='ffill', inplace=True)

C:\Users\Aarya Bhave\AppData\Local\Temp\ipykernel_28904\3502421046.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[cols].fillna(method='ffill', inplace=True)
C:\Users\Aarya Bhave\AppData\Local\Temp\ipykernel_28904\3502421046.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[cols].fillna(method='ffill', inplace=True)

In [18]:
print("Count of null values : \n",df.isnull().sum())

Count of null values :
 S.no.                      0
Name of the show           0
Year of release            0
No of seasons available    0
Language                   0
Genre                      0
IMDb rating                0
Age of viewers             0
dtype: int64

In [19]:
# removing duplicates
df.drop_duplicates(inplace=True)
print("Checking the new number of duplicates : ",df.duplicated().sum())

Checking the new number of duplicates :  0

In [ ]:
# applying encoding techniques

print(df.dtypes)
le = LabelEncoder()

for cols in columns:
    if df[cols].dtype == "object":
        df["encoded"+cols] = le.fit_transform(df[cols])

df.head(2)
print("\nAfter encoding : \n", df.dtypes)

S.no.                        int64
Name of the show            object
Year of release            float64
No of seasons available    float64
Language                    object
Genre                       object
IMDb rating                float64
Age of viewers              object
dtype: object

After encoding :
 S.no.                        int64
Name of the show            object
Year of release            float64
No of seasons available    float64
Language                    object
Genre                       object
IMDb rating                float64
Age of viewers              object
encodedName of the show      int64
encodedLanguage              int64
encodedGenre                 int64
encodedAge of viewers        int64
dtype: object

In [21]:
# removing the unrequired columns

for cols in columns:
    if df[cols].dtype =='object':
        df.drop([cols], axis=1, inplace=True)

In [22]:
df.head(2)

,S.no.,Year of release,No of seasons available,IMDb rating,encodedName of the show,encodedLanguage,encodedGenre,encodedAge of viewers
0,1,2020.0,1.0,7.5,219,4,11,2
1,2,2020.0,1.0,8.1,372,1,44,1

In [24]:
# applying normalisation, standardisation

normalisation = MinMaxScaler()
standardisation = StandardScaler()

df_normalised = normalisation.fit_transform(df[['Year of release', 'No of seasons available']])
df_standardised = standardisation.fit_transform(df)

print("Normalisation \n",df_normalised)
print("Standardisation \n",df_standardised)

Normalisation
 [[1.         0.        ]
 [1.         0.        ]
 [0.96808511 0.10526316]
 [0.9893617  0.05263158]
 [0.95744681 0.05263158]
 [0.9893617  0.        ]
 [0.9787234  0.05263158]
 [0.9787234  0.        ]
 [0.9893617  0.        ]
 [0.9893617  0.        ]
 [0.9787234  0.05263158]
 [0.96808511 0.05263158]
 [0.9893617  0.05263158]
 [0.9893617  0.05263158]
 [1.         0.        ]
 [0.9893617  0.        ]
 [0.9787234  0.        ]
 [1.         0.        ]
 [0.9787234  0.05263158]
 [1.         0.        ]
 [1.         0.        ]
 [0.94680851 0.15789474]
 [0.9893617  0.        ]
 [0.9893617  0.        ]
 [0.96808511 0.05263158]
 [0.9787234  0.05263158]
 [0.9893617  0.        ]
 [0.9787234  0.15789474]
 [0.90425532 0.36842105]
 [0.84042553 0.63157895]
 [0.84042553 0.73684211]
 [0.88297872 0.31578947]
 [1.         0.        ]
 [0.96808511 0.05263158]
 [0.84042553 0.36842105]
 [0.9787234  0.10526316]
 [0.89361702 0.36842105]
 [0.9893617  0.        ]
 [0.94680851 0.10526316]
 [0.85106383 0.73684211]
 [0.85106383 0.36842105]
 [0.95744681 0.05263158]
 [0.95744681 0.21052632]
 [0.89361702 0.31578947]
 [0.95744681 0.10526316]
 [0.9787234  0.        ]
 [0.94680851 0.15789474]
 [0.90425532 0.47368421]
 [0.93617021 0.15789474]
 [0.89361702 0.26315789]
 [0.9787234  0.        ]
 [0.96808511 0.10526316]
 [0.64893617 0.15789474]
 [0.90425532 0.15789474]
 [0.9893617  0.        ]
 [0.9893617  0.05263158]
 [0.92553191 0.21052632]
 [0.95744681 0.05263158]
 [0.95744681 0.        ]
 [0.93617021 0.21052632]
 [0.9787234  0.05263158]
 [0.9787234  0.        ]
 [0.93617021 0.21052632]
 [0.9893617  0.        ]
 [0.9787234  0.05263158]
 [0.9893617  0.05263158]
 [0.96808511 0.05263158]
 [0.88297872 0.21052632]
 [0.91489362 0.21052632]
 [0.93617021 0.21052632]
 [0.96808511 0.        ]
 [0.9893617  0.        ]
 [0.9893617  0.05263158]
 [1.         0.        ]
 [0.94680851 0.21052632]
 [0.96808511 0.05263158]
 [0.94680851 0.26315789]
 [0.92553191 0.31578947]
 [0.92553191 0.15789474]
 [0.82978723 0.84210526]
 [0.92553191 0.15789474]
 [0.94680851 0.10526316]
 [0.9787234  0.        ]
 [0.94680851 0.        ]
 [0.89361702 0.21052632]
 [0.96808511 0.10526316]
 [0.9787234  0.        ]
 [0.94680851 0.21052632]
 [0.9787234  0.10526316]
 [0.82978723 0.42105263]
 [0.9787234  0.05263158]
 [0.91489362 0.26315789]
 [0.86170213 0.15789474]
 [0.95744681 0.10526316]
 [0.93617021 0.05263158]
 [0.95744681 0.10526316]
 [0.9787234  0.10526316]
 [0.9787234  0.05263158]
 [0.96808511 0.10526316]
 [0.95744681 0.        ]
 [0.90425532 0.47368421]
 [0.96808511 0.05263158]
 [0.89361702 0.31578947]
 [0.89361702 0.21052632]
 [1.         0.        ]
 [0.86170213 0.31578947]
 [0.9787234  0.        ]
 [0.94680851 0.        ]
 [0.95744681 0.05263158]
 [0.93617021 0.05263158]
 [0.9893617  0.05263158]
 [0.9893617  0.        ]
 [0.91489362 0.26315789]
 [0.9787234  0.        ]
 [0.9787234  0.        ]
 [0.96808511 0.05263158]
 [0.87234043 0.15789474]
 [0.9893617  0.        ]
 [0.90425532 0.47368421]
 [0.93617021 0.10526316]
 [0.96808511 0.10526316]
 [0.91489362 0.05263158]
 [0.89361702 0.26315789]
 [0.9787234  0.05263158]
 [0.95744681 0.15789474]
 [0.96808511 0.        ]
 [0.96808511 0.10526316]
 [0.96808511 0.10526316]
 [0.96808511 0.10526316]
 [0.76595745 0.21052632]
 [0.9787234  0.        ]
 [0.95744681 0.10526316]
 [0.95744681 0.15789474]
 [0.93617021 0.10526316]
 [0.91489362 0.21052632]
 [0.93617021 0.05263158]
 [0.89361702 0.10526316]
 [0.9787234  0.        ]
 [0.93617021 0.15789474]
 [0.64893617 0.21052632]
 [0.9787234  0.        ]
 [1.         0.        ]
 [0.92553191 0.26315789]
 [0.93617021 0.05263158]
 [0.96808511 0.        ]
 [0.94680851 0.        ]
 [0.90425532 0.        ]
 [0.9787234  0.        ]
 [0.96808511 0.        ]
 [0.95744681 0.        ]
 [0.95744681 0.        ]
 [0.94680851 0.05263158]
 [0.9893617  0.        ]
 [0.96808511 0.        ]
 [0.86170213 0.05263158]
 [0.62765957 0.31578947]
 [0.93617021 0.05263158]
 [0.9787234  0.        ]
 [0.88297872 0.        ]
 [0.95744681 0.        ]
 [0.94680851 0.        ]
 [0.96808511 0.05263158]
 [0.9893617  0.        ]
 [0.9787234  0.        ]
 [0.70212766 0.15789474]
 [0.93617021 0.21052632]
 [0.96808511 0.        ]
 [0.9893617  0.        ]
 [0.96808511 0.05263158]
 [0.84042553 0.        ]
 [0.9787234  0.        ]
 [0.9787234  0.        ]
 [0.96808511 0.        ]
 [0.9787234  0.        ]
 [0.80851064 0.        ]
 [0.9893617  0.        ]
 [0.95744681 0.05263158]
 [0.96808511 0.05263158]
 [0.96808511 0.        ]
 [0.9893617  0.        ]
 [0.9893617  0.05263158]
 [0.94680851 0.        ]
 [0.95744681 0.        ]
 [0.9787234  0.        ]
 [0.31914894 0.        ]
 [0.93617021 0.        ]
 [0.94680851 0.        ]
 [0.92553191 0.        ]
 [0.95744681 0.        ]
 [0.70212766 0.15789474]
 [0.74468085 0.31578947]
 [0.86170213 0.        ]
 [0.9787234  0.        ]
 [0.95744681 0.05263158]
 [0.95744681 0.        ]
 [0.9787234  0.        ]
 [0.93617021 0.        ]
 [0.9893617  0.        ]
 [0.63829787 0.05263158]
 [0.60638298 0.        ]
 [0.9787234  0.        ]
 [0.         0.        ]
 [0.95744681 0.10526316]
 [0.94680851 0.21052632]
 [0.9893617  0.        ]
 [0.94680851 0.        ]
 [0.35106383 0.10526316]
 [0.95744681 0.15789474]
 [0.9787234  0.05263158]
 [0.68085106 0.        ]
 [0.84042553 0.        ]
 [0.36170213 0.        ]
 [0.86170213 0.        ]
 [0.68085106 0.21052632]
 [0.63829787 0.26315789]
 [0.96808511 0.        ]
 [0.9787234  0.        ]
 [0.75531915 0.05263158]
 [0.71276596 0.        ]
 [0.84042553 0.        ]
 [0.9893617  0.        ]
 [0.87234043 0.        ]
 [0.93617021 0.21052632]
 [0.94680851 0.        ]
 [0.95744681 0.10526316]
 [0.95744681 0.        ]
 [0.96808511 0.05263158]
 [0.96808511 0.        ]
 [0.92553191 0.05263158]
 [0.76595745 1.        ]
 [0.92553191 0.        ]
 [0.78723404 0.10526316]
 [0.9787234  0.        ]
 [0.9787234  0.15789474]
 [0.69148936 0.10526316]
 [0.9787234  0.05263158]
 [0.88297872 0.        ]
 [0.94680851 0.05263158]
 [0.88297872 0.        ]
 [0.79787234 0.05263158]
 [0.92553191 0.05263158]
 [0.96808511 0.        ]
 [0.31914894 0.15789474]
 [0.9893617  0.        ]
 [0.90425532 0.        ]
 [0.56382979 0.        ]
 [0.71276596 0.21052632]
 [0.93617021 0.05263158]
 [0.94680851 0.05263158]
 [0.63829787 0.05263158]
 [0.32978723 0.        ]
 [0.87234043 0.05263158]
 [0.35106383 0.        ]
 [0.93617021 0.        ]
 [0.9893617  0.        ]
 [0.58510638 0.10526316]
 [0.73404255 0.        ]
 [0.91489362 0.05263158]
 [0.9787234  0.10526316]
 [0.87234043 0.57894737]
 [0.84042553 0.42105263]
 [0.73404255 0.        ]
 [0.9893617  0.        ]
 [0.95744681 0.10526316]
 [0.91489362 0.26315789]
 [0.95744681 0.05263158]
 [0.84042553 0.        ]
 [0.81914894 0.57894737]
 [0.9787234  0.05263158]
 [1.         0.        ]
 [0.36170213 0.05263158]
 [0.9787234  0.05263158]
 [0.93617021 0.        ]
 [0.86170213 0.36842105]
 [0.93617021 0.31578947]
 [0.61702128 0.        ]
 [0.76595745 0.31578947]
 [0.95744681 0.        ]
 [0.77659574 0.21052632]
 [0.89361702 0.42105263]
 [0.71276596 0.        ]
 [0.68085106 0.42105263]
 [0.88297872 0.31578947]
 [0.91489362 0.        ]
 [0.9787234  0.        ]
 [0.69148936 0.26315789]
 [1.         0.        ]
 [0.94680851 0.        ]
 [0.91489362 0.21052632]
 [0.87234043 0.21052632]
 [0.92553191 0.26315789]
 [0.86170213 0.        ]
 [0.76595745 0.15789474]
 [0.86170213 0.31578947]
 [0.96808511 0.        ]
 [0.94680851 0.15789474]
 [0.95744681 0.        ]
 [0.91489362 0.21052632]
 [0.96808511 0.        ]
 [0.93617021 0.        ]
 [0.9787234  0.        ]
 [0.62765957 0.05263158]
 [0.57446809 0.15789474]
 [0.96808511 0.        ]
 [0.74468085 0.        ]
 [1.         0.        ]
 [0.63829787 0.05263158]
 [0.96808511 0.        ]
 [0.92553191 0.05263158]
 [0.9893617  0.        ]
 [0.95744681 0.        ]
 [0.78723404 0.15789474]
 [0.96808511 0.05263158]
 [0.94680851 0.        ]
 [1.         0.        ]
 [0.94680851 0.10526316]
 [0.94680851 0.        ]
 [0.9893617  0.        ]
 [0.9787234  0.        ]
 [0.43617021 0.21052632]
 [0.9787234  0.05263158]
 [1.         0.        ]
 [1.         0.        ]
 [0.91489362 0.05263158]
 [0.65957447 0.        ]
 [0.82978723 0.15789474]
 [0.95744681 0.15789474]
 [0.9787234  0.05263158]
 [0.9893617  0.        ]
 [0.96808511 0.        ]
 [0.96808511 0.        ]
 [0.95744681 0.        ]
 [0.9787234  0.        ]
 [0.95744681 0.        ]
 [0.9893617  0.        ]
 [0.95744681 0.15789474]
 [0.9787234  0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.96808511 0.15789474]
 [0.9787234  0.05263158]
 [0.86170213 0.10526316]
 [0.95744681 0.05263158]
 [0.75531915 0.15789474]
 [0.9787234  0.        ]
 [1.         0.        ]
 [0.95744681 0.05263158]
 [0.95744681 0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.95744681 0.        ]
 [0.9893617  0.        ]
 [0.9893617  0.        ]
 [1.         0.        ]
 [0.9893617  0.        ]
 [0.9787234  0.        ]
 [1.         0.        ]
 [0.9787234  0.05263158]
 [0.77659574 0.05263158]
 [0.96808511 0.        ]
 [1.         0.        ]
 [0.9893617  0.        ]
 [0.9893617  0.        ]
 [0.94680851 0.        ]
 [0.96808511 0.05263158]
 [0.9893617  0.        ]
 [1.         0.        ]
 [0.94680851 0.        ]
 [0.96808511 0.        ]
 [0.95744681 0.        ]
 [0.9893617  0.        ]
 [0.9787234  0.        ]
 [0.34042553 0.10526316]
 [0.9787234  0.10526316]
 [0.9787234  0.        ]
 [0.9787234  0.        ]
 [0.36170213 0.        ]
 [0.9787234  0.05263158]
 [0.81914894 0.        ]
 [0.9893617  0.05263158]
 [0.85106383 0.        ]
 [0.96808511 0.05263158]
 [0.34042553 0.26315789]
 [0.9787234  0.        ]
 [0.96808511 0.        ]
 [0.9893617  0.05263158]
 [0.94680851 0.15789474]
 [0.9893617  0.        ]
 [0.93617021 0.        ]
 [0.9787234  0.        ]
 [0.96808511 0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]]
Standardisation
 [[-1.72776885  0.66116481 -0.60950503 ...  1.02611893 -0.26186332
   0.26013351]
 [-1.71919431  0.66116481 -0.60950503 ... -0.41163384  2.4892492
  -0.50697553]
 [-1.71061978  0.42733588  0.16973558 ... -0.41163384  0.23833896
  -0.50697553]
 ...
 [ 1.71061978  0.66116481 -0.60950503 ... -0.41163384 -0.67869855
  -0.50697553]
 [ 1.71919431  0.66116481 -0.60950503 ... -0.41163384 -0.67869855
  -0.50697553]
 [ 1.72776885  0.66116481 -0.60950503 ... -0.41163384 -0.67869855
  -0.50697553]]