In [44]:
print("Aarya Bhave\nB24CE1110\nTY-2\nDSML Assignment 4")

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

Aarya Bhave
B24CE1110
TY-2
DSML Assignment 4

In [45]:
df = pd.read_csv("C:/codes/dsml/AAPL.csv/AAPL.csv")
df.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.406782  117258400
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.385558   43971200
2  1980-12-16  0.453125  0.453125  0.450893  0.450893   0.357260   26432000
3  1980-12-17  0.462054  0.464286  0.462054  0.462054   0.366103   21610400
4  1980-12-18  0.475446  0.477679  0.475446  0.475446   0.376715   18362400

In [46]:
# Performing EDA
print("Data Information \n", df.info())
print("Data Shape : ", df.shape)
print("Data Description : \n", df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9909 entries, 0 to 9908
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       9909 non-null   object
 1   Open       9909 non-null   float64
 2   High       9909 non-null   float64
 3   Low        9909 non-null   float64
 4   Close      9909 non-null   float64
 5   Adj Close  9909 non-null   float64
 6   Volume     9909 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 542.0+ KB
Data Information
 None
Data Shape :  (9909, 7)
Data Description :
               Open         High          Low        Close    Adj Close  \
count  9909.000000  9909.000000  9909.000000  9909.000000  9909.000000
mean     32.606849    32.936079    32.277560    32.618030    30.576570
std      58.415759    59.001576    57.883037    58.471899    56.746275
min       0.198661     0.198661     0.196429     0.196429     0.155638
25%       1.071429     1.089286     1.048571     1.071429     0.917643
50%       1.729286     1.758929     1.696429     1.732143     1.466154
75%      35.799999    36.265713    35.328571    35.761429    31.042374
max     324.739990   327.850006   323.350006   327.200012   327.200012

             Volume
count  9.909000e+03
mean   8.582916e+07
std    8.597195e+07
min    3.472000e+05
25%    3.304230e+07
50%    5.766490e+07
75%    1.069992e+08
max    1.855410e+09

In [47]:
# Checking basic requirements for the data
print("Null Count : ", df.isnull().sum())
df.dropna()

Null Count :  Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.513393,0.515625,0.513393,0.513393,0.406782,117258400
1,1980-12-15,0.488839,0.488839,0.486607,0.486607,0.385558,43971200
2,1980-12-16,0.453125,0.453125,0.450893,0.450893,0.357260,26432000
3,1980-12-17,0.462054,0.464286,0.462054,0.462054,0.366103,21610400
4,1980-12-18,0.475446,0.477679,0.475446,0.475446,0.376715,18362400
...,...,...,...,...,...,...,...
9904,2020-03-26,246.520004,258.679993,246.360001,258.440002,258.440002,63021800
9905,2020-03-27,252.750000,255.869995,247.050003,247.740005,247.740005,51054200
9906,2020-03-30,250.740005,255.520004,249.399994,254.809998,254.809998,41994100
9907,2020-03-31,255.600006,262.489990,252.000000,254.289993,254.289993,49250500
9908,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.910004,43956200

In [48]:
df.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.406782  117258400
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.385558   43971200
2  1980-12-16  0.453125  0.453125  0.450893  0.450893   0.357260   26432000
3  1980-12-17  0.462054  0.464286  0.462054  0.462054   0.366103   21610400
4  1980-12-18  0.475446  0.477679  0.475446  0.475446   0.376715   18362400

In [49]:
y = df['Close']
X = df[['Open', 'High', 'Low', 'Adj Close', 'Volume']]

In [50]:
print("Input Data", X.columns)
print("Prediction Data: Close" )

Input Data Index(['Open', 'High', 'Low', 'Adj Close', 'Volume'], dtype='object')
Prediction Data: Close

In [51]:
# applying train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 24
)

In [52]:
print("Training Data Shape : ", X_train.shape)
print("Testing Data Shape : ", X_test.shape)

Training Data Shape :  (7927, 5)
Testing Data Shape :  (1982, 5)

In [53]:
# Scaling the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [54]:
# Applying Gradient Descent
import numpy as np
def linear_gd(X, y, lr=0.01, epochs=1000, alpha=0.1):
    n, m = X.shape
    w = np.zeros(m)
    b = 0

    for i in range(epochs):
        pred = np.dot(X, w) + b
        loss = pred - y

        dw = (2/n) * np.dot(X.T, loss)
        db = (2/n) * np.sum(loss)

        w -= lr * dw
        b -= lr * db

    return w,b

def ridge_gd(X, y, lr=0.01, epochs=1000, alpha=0.1):
    n, m = X.shape
    w = np.zeros(m)
    b = 0

    for i in range(epochs):
        pred = np.dot(X, w) + b
        loss = pred - y

        dw = (2/n) * np.dot(X.T, loss) +2 * alpha * w
        db = (2/n) * np.sum(loss)

        w -= lr * dw
        b -= lr * db

    return w,b

def lasso_gd(X, y, lr=0.01, epochs=1000, alpha=0.1):
    n, m = X.shape
    w = np.zeros(m)
    b = 0

    for i in range(epochs):
        pred = np.dot(X, w) + b
        loss = pred - y

        dw = (2/n) * np.dot(X.T, loss) + alpha *np.sign(w)
        db = (2/n) * np.sum(loss)

        w -= lr * dw
        b -= lr * db

    return w,b

In [55]:
w_linear, b_linear = linear_gd(X_train_scaled, y_train.values)
pred_linear = np.dot(X_test_scaled, w_linear) + b_linear
print("Linear Regression Successfull")

Linear Regression Successfull

In [56]:
w_ridge, b_ridge = ridge_gd(X_train_scaled, y_train.values, alpha=0.1)
pred_ridge = np.dot(X_test_scaled, w_ridge) + b_ridge
print("Ridge Regression Successfull")

Ridge Regression Successfull

In [57]:
w_lasso, b_lasso = lasso_gd(X_train_scaled, y_train.values, alpha=0.1)
pred_lasso = np.dot(X_test_scaled, w_lasso) + b_lasso
print("Lasso Regression Successfull")

Lasso Regression Successfull

In [58]:
def evaluate(name, actual, predicted):
    mae = mean_absolute_error(actual, predicted)
    rmse = np.sqrt(mean_squared_error(actual, predicted))
    r2 = r2_score(actual, predicted)


    print("Regression Type : ", name)
    print("MAE : ", mae)
    print("RMSE : ", rmse)
    print("R2 :", r2)
    print("\n")

    return name, mae, rmse, r2

In [59]:
linear_result = evaluate("Linear Regression", y_test, pred_linear)
ridge_result = evaluate("Ridge Regression", y_test, pred_ridge)
lasso_result = evaluate("Lasso Regression", y_test, pred_lasso)

Regression Type :  Linear Regression
MAE :  0.4157743164372263
RMSE :  0.6873748428158596
R2 : 0.9998641342895954


Regression Type :  Ridge Regression
MAE :  1.3200159817293144
RMSE :  1.6244167084338033
R2 : 0.9992412171734327


Regression Type :  Lasso Regression
MAE :  0.44605297025259705
RMSE :  0.694975125282751
R2 : 0.999861113153169

In [60]:
train_linear = np.dot(X_train_scaled, w_linear) + b_linear
train_ridge = np.dot(X_train_scaled, w_ridge) + b_ridge
train_lasso = np.dot(X_train_scaled, w_lasso) + b_lasso

print("Comparing the training; the testing accuracy")
print("Linear Regression")
print("Training R2 : ", r2_score(y_train, train_linear))
print("testing R2 :", r2_score(y_test, pred_linear))

print("Ridge Regression")
print("Training R2 : ", r2_score(y_train, train_ridge))
print("testing R2 :", r2_score(y_test, pred_ridge))

print("Lasso Regression")
print("Training R2 : ", r2_score(y_train, train_lasso))
print("testing R2 :", r2_score(y_test, pred_lasso))

Comparing the training; the testing accuracy
Linear Regression
Training R2 :  0.9998292719574086
testing R2 : 0.9998641342895954
Ridge Regression
Training R2 :  0.9992221331688529
testing R2 : 0.9992412171734327
Lasso Regression
Training R2 :  0.9998276390162264
testing R2 : 0.999861113153169

In [61]:
kf = KFold(n_splits = 5, shuffle = True, random_state= 21)

scores = []

for train_idx, val_idx in kf.split(X):
    X_tr = X.iloc[train_idx]
    X_val = X.iloc[val_idx]

    y_tr = y.iloc[train_idx]
    y_val = y.iloc[val_idx]

    fold_scaler = StandardScaler()

    X_tr = fold_scaler.fit_transform(X_tr)
    X_val = fold_scaler.transform(X_val)

    w, b = linear_gd(X_tr, y_tr.values)
    pred = np.dot(X_val, w) + b

    score = r2_score(y_val, pred)
    scores.append(score)

print("R2 Scores using cross-validation")
print(scores)

R2 Scores using cross-validation
[0.9998237070055265, 0.9998363198313823, 0.9998385101933502, 0.9998337868170617, 0.9998471789248867]